### ISSUE TITLE
GRPlatform>>selectorOfPragma: appears unimplemented

### ISSUE THREAD

**Issue by timrowledge** [SeasideSt/Grease#132]
I've just stumbled over WARouteBuilder class>>#createRoutesFrom:to: failing because GRPlatform>>#selectorOfPragma: is the only implementation and is a subclassResponsibilty method.

I have tried poking around the code in github but don't see any concrete implementation anywhere. For Squeak it is merely ^pragma keyword, which is easy enough, but I'm not sure which package you'd like it to be in, or if it is already in some packaage I haven't spotted

**Comment by jbrichau** [comment]
The method is not part of Grease. The Seaside REST implementation has platform-specific packages and the extension method is defined in there. For example https://github.com/SeasideSt/Seaside/blob/master/repository/Seaside-Pharo90-REST-Core.package/GRPharoPlatform.extension/instance/selectorOfPragma..st

How did you load the REST functionality and on which platform?

**Comment by timrowledge** [comment]
OK, fair point.
The build of Seaside was done last March (2021) with the following code
```Installer ensureRecentMetacello.

"Load Seaside" 
Metacello new
baseline:'Seaside3';
repository: 'github://SeasideSt/Seaside:master/repository';
load;
load: #('REST' 'Scriptaculous').
```
... into a Squeak 5.3 image.

Everything else has being doing sterling service.

**Comment by jbrichau** [comment]
Unfortunately, the Squeak build for Seaside has been unstable for years now and I am unable to continue supporting it by myself. I kept the builds in the line up but never checked on their real status anymore. What was just a couple of failing tests for Squeak has, understandably, evolved to more failing tests. 

I notice the build does pick up your issue: https://github.com/SeasideSt/Seaside/runs/4685300908?check_suite_focus=true
It should therefore be relatively straightforward to add the implementation in a Squeak-specific package and add it to the baseline. If you are willing to make the changes and submit a PR (against the Seaside project), I can further assist such that the changes are merged in. 

Getting all the Squeak builds green again would be great as well. So, any assistance is greatly appreciated!

**Comment by tcj** [comment]
On Fri, 7 Jan 2022, Johan Brichau wrote:

> Getting all the Squeak builds green again would be great as well. So, any
> assistance is greatly appreciated!

Hi!  I committed/volunteered to work on this a few years ago, but then 
disappeared.  (Sorry...)

Life is changing again in such a way that I could begin to dig into this & 
maintain the commitment, and/or help where needed.

Q: A few years ago, all the pieces were aligned ... Squeak had all the 
necessary Metacello pieces to manipulate Seaside & Grease packages from 
GitHub.  Is that still true?  I ask because I recall it was problematic to 
work with some Tonel packages in Squeak, when I last tried a few years 
ago.  But I also think (1) that may have been addressed and (2) I recall 
Seaside/Grease were not using Tonel at the time, and I imagine that hasn't 
changed.

Thanks,
Tim J

**Comment by jbrichau** [comment]
Last time I checked was over a year ago and I was able to follow the Squeak install instructions to make some changes in the context of https://github.com/SeasideSt/Seaside/issues/1195. I cannot really say anything beyond that point.

We keep using filetree for now since only Pharo has full support for that format. This will most likely change in the future, but not tomorrow.

As I said, I can assist and will help where I can to maintain Seaside running on Squeak, but someone who is actively using Seaside (and Grease) in Squeak is going to need to make the necessary changes via pull requests.

**Comment by timrowledge** [comment]
The practical problem I have is a complete lack of setup for using git with Squeak, except whatever gets loaded as a result of  the above Metacello install. If I make a suitable method that appears in the appropriate package (*seaside-rest-core) there seems to be no plausible way to submit it.

The fileout is trivial 
```
'From Squeak5.3 of 15 April 2020 [latest update: #19435] on 13 January 2022 at 6:16:37 pm'!

!GRSqueakPlatform methodsFor: '*seaside-rest-core' stamp: 'tpr 1/13/2022 18:13'!
selectorOfPragma: aPragma

	^aPragma keyword! !

```
What needs doing to make this 'pull request' thing?

**Comment by tcj** [comment]
Hi Tim,

I can probably help turn your fileOut into a PR... I'll look at it over 
the next ~24 hours.

As I recall, adding a commit to an extension package requires special 
care...?  A bit rusty, haven't touched this stuff in ~2 years.

Tim J

**Comment by jbrichau** [comment]
Since Iceberg exists in Pharo for several years now, the procedure to commit to git using external git tools is unused, but there still is info available in https://github.com/SeasideSt/Seaside/blob/master/CONTRIBUTING.md#checkout

**Comment by tcj** [comment]
I've submitted my PR against the Seaside repo, but expect it will be rejected due to all the unnecessary/unfortunate method metadata changes...?

https://github.com/SeasideSt/Seaside/pull/1301

I'd be happy to write up my process, but let's wait to see if this is merged or not.

Side note unrelated to Grease:

Ignoring all "only different timestamp" changes in Squeak's Monticello commit UI is an unfortunate necessity here.  I think this is due to the Cypress conversion and timestamps?  I knew more about this in 2019, thanks to some coaching back then from Dale H. and others, but it's become foggier now.

I ignored (cmd-shift-i) all methods-with-only-changed-timestamps in Squeak's Monticello commit UI, but Squeak-flavored Metacello (or its subsystems/Filetree/Cypress) _still included method metadata changes for those ignored methods_ in the eventual commit.  (Something about the `fabricated from a Cypress format repository` situation?)  I've forgotten whether there was a workaround for this (telling Filetree to ignore timestamps?), but recall there may have been...?  And I think it was a parameter that goes into the `.filetree` file?

```
old:  1/14/2022 17:11:31 accessing  
new:  1/14/2022 17:10:38 accessing
```

```
#       new file:   repository/Seaside-REST-Core.package/WARouteResult.class/methodProperties.json
#       modified:   repository/Seaside-REST-Core.package/WARouteResult.class/properties.json
```
